export const data = [
    {
      data_year: 2015,
      "Aggravated Assault": 1734,
      "All Other Offenses (Except Traffic)": 13025,
      Arson: 67,
      Burglary: 485,
      "Curfew and Loitering Law Violations": 5,
      "Disorderly Conduct": 795,
      "Driving Under the Influence": 3163,
      "Drug Abuse Violations - Grand Total": 1212,
      Drunkenness: 80,
      Embezzlement: 72,
      "Forgery and Counterfeiting": 39,
      Fraud: 230,
      "Gambling - Total": 0,
      "Human Trafficking - Commercial Sex Acts": 0,
      "Human Trafficking - Involuntary Servitude": 0,
      "Larceny - Theft": 2540,
      "Liquor Laws": 1100,
      "Manslaughter by Negligence": 1,
      "Motor Vehicle Theft": 361,
      "Murder and Nonnegligent Manslaughter": 47,
      "Offenses Against the Family and Children": 181,
      "Prostitution and Commercialized Vice": 8,
      Rape: 118,
      Robbery: 294,
      "Simple Assault": 4350,
      "Stolen Property: Buying, Receiving, Possessing": 52,
      Suspicion: 0,
      Vagrancy: 3,
      Vandalism: 898,
      "Weapons: Carrying, Possessing, Etc.": 303,
      "Sex Offenses (Except Rape, and Prostitution and Commercialized Vice)": 240,
    },
    {
      data_year: 2016,
      "Aggravated Assault": 1845,
      "All Other Offenses (Except Traffic)": 11340,
      Arson: 51,
      "Burglary": 538,
      "Curfew and Loitering Law Violations": 12,
      "Disorderly Conduct": 738,
      "Driving Under the Influence": 3063,
      "Drug Abuse Violations - Grand Total": 1006,
      Drunkenness: 112,
      Embezzlement: 81,
      "Forgery and Counterfeiting": 96,
      Fraud: 236,
      "Gambling - Total": 0,
      "Human Trafficking - Commercial Sex Acts": 0,
      "Human Trafficking - Involuntary Servitude": 0,
      "Larceny - Theft": 2401,
      "Liquor Laws": 775,
      "Manslaughter by Negligence": 5,
      "Motor Vehicle Theft": 505,
      "Murder and Nonnegligent Manslaughter": 41,
      "Offenses Against the Family and Children": 195,
      "Prostitution and Commercialized Vice": 13,
      Rape: 130,
      Robbery: 282,
      "Simple Assault": 4300,
      "Stolen Property: Buying, Receiving, Possessing": 82,
      Suspicion: 0,
      Vagrancy: 4,
      Vandalism: 1024,
      "Weapons: Carrying, Possessing, Etc.": 311,
      "Sex Offenses (Except Rape, and Prostitution and Commercialized Vice)": 281,
    },
    {
      data_year: 2017,
      "Aggravated Assault": 1913,
      "All Other Offenses (Except Traffic)": 10737,
      Arson: 22,
      Burglary: 623,
      "Curfew and Loitering Law Violations": 0,
      "Disorderly Conduct": 757,
      "Driving Under the Influence": 3102,
      "Drug Abuse Violations - Grand Total": 1004,
      Drunkenness: 43,
      Embezzlement: 77,
      "Forgery and Counterfeiting": 113,
      Fraud: 219,
      "Gambling - Total": 0,
      "Human Trafficking - Commercial Sex Acts": 0,
      "Human Trafficking - Involuntary Servitude": 0,
      "Larceny - Theft": 2356,
      "Liquor Laws": 653,
      "Manslaughter by Negligence": 2,
      "Motor Vehicle Theft": 694,
      "Murder and Nonnegligent Manslaughter": 46,
      "Offenses Against the Family and Children": 159,
      "Prostitution and Commercialized Vice": 5,
      Rape: 126,
      Robbery: 289,
      "Simple Assault": 4478,
      "Stolen Property: Buying, Receiving, Possessing": 105,
      Suspicion: 0,
      Vagrancy: 2,
      Vandalism: 1004,
      "Weapons: Carrying, Possessing, Etc.": 369,
      "Sex Offenses (Except Rape, and Prostitution and Commercialized Vice)": 256,
    },
    {
      data_year: 2018,
      "Aggravated Assault": 2132,
      "All Other Offenses (Except Traffic)": 11072,
      Arson: 43,
      Burglary: 602,
      "Curfew and Loitering Law Violations": 5,
      "Disorderly Conduct": 843,
      "Driving Under the Influence": 3148,
      "Drug Abuse Violations - Grand Total": 1046,
      Drunkenness: 47,
      Embezzlement: 54,
      "Forgery and Counterfeiting": 154,
      Fraud: 201,
      "Gambling - Total": 0,
      "Human Trafficking - Commercial Sex Acts": 0,
      "Human Trafficking - Involuntary Servitude": 0,
      "Larceny - Theft": 2392,
      "Liquor Laws": 592,
      "Manslaughter by Negligence": 4,
      "Motor Vehicle Theft": 726,
      "Murder and Nonnegligent Manslaughter": 38,
      "Offenses Against the Family and Children": 174,
      "Prostitution and Commercialized Vice": 2,
      Rape: 149,
      Robbery: 367,
      "Simple Assault": 4943,
      "Stolen Property: Buying, Receiving, Possessing": 120,
      Suspicion: 0,
      Vagrancy: 17,
      Vandalism: 1103,
      "Weapons: Carrying, Possessing, Etc.": 387,
      "Sex Offenses (Except Rape, and Prostitution and Commercialized Vice)": 263,
    },
    {
      data_year: 2019,
      "Aggravated Assault": 2077,
      "All Other Offenses (Except Traffic)": 10179,
      Arson: 49,
      Burglary: 603,
      "Curfew and Loitering Law Violations": 0,
      "Disorderly Conduct": 742,
      "Driving Under the Influence": 2856,
      "Drug Abuse Violations - Grand Total": 930,
      Drunkenness: 31,
      Embezzlement: 43,
      "Forgery and Counterfeiting": 78,
      Fraud: 121,
      "Gambling - Total": 0,
      "Human Trafficking - Commercial Sex Acts": 0,
      "Human Trafficking - Involuntary Servitude": 0,
      "Larceny - Theft": 1885,
      "Liquor Laws": 310,
      "Manslaughter by Negligence": 4,
      "Motor Vehicle Theft": 476,
      "Murder and Nonnegligent Manslaughter": 46,
      "Offenses Against the Family and Children": 150,
      "Prostitution and Commercialized Vice": 5,
      Rape: 129,
      Robbery: 310,
      "Simple Assault": 4862,
      "Stolen Property: Buying, Receiving, Possessing": 91,
      Suspicion: 0,
      Vagrancy: 2,
      Vandalism: 1161,
      "Weapons: Carrying, Possessing, Etc.": 259,
      "Sex Offenses (Except Rape, and Prostitution and Commercialized Vice)": 243,
    },
    {
      data_year: 2020,
      "Aggravated Assault": 2118,
      "All Other Offenses (Except Traffic)": 9865,
      Arson: 42,
      Burglary: 471,
      "Curfew and Loitering Law Violations": 0,
      "Disorderly Conduct": 655,
      "Driving Under the Influence": 3008,
      "Drug Abuse Violations - Grand Total": 808,
      Drunkenness: 19,
      Embezzlement: 35,
      "Forgery and Counterfeiting": 53,
      Fraud: 199,
      "Gambling - Total": 0,
      "Human Trafficking - Commercial Sex Acts": 0,
      "Human Trafficking - Involuntary Servitude": 0,
      "Larceny - Theft": 1545,
      "Liquor Laws": 275,
      "Manslaughter by Negligence": 1,
      "Motor Vehicle Theft": 338,
      "Murder and Nonnegligent Manslaughter": 33,
      "Offenses Against the Family and Children": 101,
      "Prostitution and Commercialized Vice": 1,
      Rape: 160,
      Robbery: 287,
      "Simple Assault": 4591,
      "Stolen Property: Buying, Receiving, Possessing": 66,
      Suspicion: 2,
      Vagrancy: 44,
      Vandalism: 1063,
      "Weapons: Carrying, Possessing, Etc.": 332,
      "Sex Offenses (Except Rape, and Prostitution and Commercialized Vice)": 242,
    },
  ];


  export const getData = async () => {
    const apiUrl = 'https://api.usa.gov/crime/fbi/cde/arrest/state/AK/all?from=2015&to=2020&API_KEY=iiHnOKfno2Mgkt5AynpvPpUQTEyxE77jo1RU8PIv';
  
    try {
      const response = await fetch(apiUrl);
  
      if (!response.ok) {
        throw new Error('Network response was not ok');
      }
  
      const data = await response.data.data;
      return data;
    } catch (error) {
      console.error('Error fetching data:', error);
      return null; 
    }
  };